import os
from dotenv import load_dotenv
from sympy import true

# Load variables from .env (project root)
load_dotenv()

AZURE_API_KEY = os.getenv("AZURE_API_KEY")
AZURE_API_VERSION = os.getenv("AZURE_API_VERSION")
AZURE_ENDPOINT = os.getenv("AZURE_ENDPOINT")
AZURE_DEPLOYMENT_NAME = os.getenv("AZURE_DEPLOYMENT_NAME")
AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
MILVUS_URI = os.getenv("MILVUS_URI")
MILVUS_COLLECTION_NAME = os.getenv("MILVUS_COLLECTION_NAME")

EMAIL_ADDRESS = os.getenv("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")
FASTAPI_MCP_API_KEY = os.getenv("FASTAPI_MCP_API_KEY")
FASTAPI_MCP_URL = os.getenv("FASTAPI_MCP_URL")

LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY")
LANGSMITH_TRACING = os.getenv("LANGSMITH_TRACING")
LANGSMITH_PROJECT = os.getenv("LANGSMITH_PROJECT")
LANGSMITH_ENDPOINT = os.getenv("LANGSMITH_ENDPOINT")
ADMIN_PANEL_PASSWORD=os.getenv("ADMIN_PANEL_PASSWORD")